/**
 * Minimal ICAO airport code → { name, city, iata } lookup for major global airports.
 * For unknown codes, the UI falls back to showing the ICAO code alone.
 */
type Airport = { name: string; city: string; iata?: string };

export const AIRPORTS: Record<string, Airport> = {
  // North America
  KJFK: { name: "John F. Kennedy Intl", city: "New York", iata: "JFK" },
  KLGA: { name: "LaGuardia", city: "New York", iata: "LGA" },
  KEWR: { name: "Newark Liberty", city: "Newark", iata: "EWR" },
  KLAX: { name: "Los Angeles Intl", city: "Los Angeles", iata: "LAX" },
  KSFO: { name: "San Francisco Intl", city: "San Francisco", iata: "SFO" },
  KSEA: { name: "Seattle-Tacoma", city: "Seattle", iata: "SEA" },
  KORD: { name: "O'Hare", city: "Chicago", iata: "ORD" },
  KMDW: { name: "Midway", city: "Chicago", iata: "MDW" },
  KATL: { name: "Hartsfield-Jackson", city: "Atlanta", iata: "ATL" },
  KDFW: { name: "Dallas/Fort Worth", city: "Dallas", iata: "DFW" },
  KIAH: { name: "Bush Intercontinental", city: "Houston", iata: "IAH" },
  KMIA: { name: "Miami Intl", city: "Miami", iata: "MIA" },
  KBOS: { name: "Logan", city: "Boston", iata: "BOS" },
  KDCA: { name: "Reagan National", city: "Washington", iata: "DCA" },
  KIAD: { name: "Dulles", city: "Washington", iata: "IAD" },
  KDEN: { name: "Denver Intl", city: "Denver", iata: "DEN" },
  KPHX: { name: "Phoenix Sky Harbor", city: "Phoenix", iata: "PHX" },
  KLAS: { name: "Harry Reid", city: "Las Vegas", iata: "LAS" },
  KMSP: { name: "Minneapolis-St. Paul", city: "Minneapolis", iata: "MSP" },
  KDTW: { name: "Detroit Metro", city: "Detroit", iata: "DTW" },
  KCLT: { name: "Charlotte Douglas", city: "Charlotte", iata: "CLT" },
  KPHL: { name: "Philadelphia Intl", city: "Philadelphia", iata: "PHL" },
  KBWI: { name: "BWI", city: "Baltimore", iata: "BWI" },
  KPDX: { name: "Portland Intl", city: "Portland", iata: "PDX" },
  KSLC: { name: "Salt Lake City Intl", city: "Salt Lake City", iata: "SLC" },
  KAUS: { name: "Austin-Bergstrom", city: "Austin", iata: "AUS" },
  KSAN: { name: "San Diego Intl", city: "San Diego", iata: "SAN" },
  KMCO: { name: "Orlando Intl", city: "Orlando", iata: "MCO" },
  KTPA: { name: "Tampa Intl", city: "Tampa", iata: "TPA" },
  KBNA: { name: "Nashville Intl", city: "Nashville", iata: "BNA" },
  KHNL: { name: "Honolulu Intl", city: "Honolulu", iata: "HNL" },
  CYYZ: { name: "Toronto Pearson", city: "Toronto", iata: "YYZ" },
  CYVR: { name: "Vancouver Intl", city: "Vancouver", iata: "YVR" },
  CYUL: { name: "Montréal-Trudeau", city: "Montréal", iata: "YUL" },
  CYYC: { name: "Calgary Intl", city: "Calgary", iata: "YYC" },
  MMMX: { name: "Mexico City Intl", city: "Mexico City", iata: "MEX" },
  MMUN: { name: "Cancún Intl", city: "Cancún", iata: "CUN" },

  // Europe
  EGLL: { name: "Heathrow", city: "London", iata: "LHR" },
  EGKK: { name: "Gatwick", city: "London", iata: "LGW" },
  EGSS: { name: "Stansted", city: "London", iata: "STN" },
  EGLC: { name: "London City", city: "London", iata: "LCY" },
  EGCC: { name: "Manchester", city: "Manchester", iata: "MAN" },
  EGPH: { name: "Edinburgh", city: "Edinburgh", iata: "EDI" },
  EIDW: { name: "Dublin", city: "Dublin", iata: "DUB" },
  LFPG: { name: "Charles de Gaulle", city: "Paris", iata: "CDG" },
  LFPO: { name: "Orly", city: "Paris", iata: "ORY" },
  EDDF: { name: "Frankfurt", city: "Frankfurt", iata: "FRA" },
  EDDM: { name: "Munich", city: "Munich", iata: "MUC" },
  EDDL: { name: "Düsseldorf", city: "Düsseldorf", iata: "DUS" },
  EDDB: { name: "Berlin Brandenburg", city: "Berlin", iata: "BER" },
  EDDH: { name: "Hamburg", city: "Hamburg", iata: "HAM" },
  EHAM: { name: "Schiphol", city: "Amsterdam", iata: "AMS" },
  EBBR: { name: "Brussels", city: "Brussels", iata: "BRU" },
  LEMD: { name: "Madrid-Barajas", city: "Madrid", iata: "MAD" },
  LEBL: { name: "Barcelona-El Prat", city: "Barcelona", iata: "BCN" },
  LIRF: { name: "Fiumicino", city: "Rome", iata: "FCO" },
  LIMC: { name: "Malpensa", city: "Milan", iata: "MXP" },
  LSZH: { name: "Zürich", city: "Zürich", iata: "ZRH" },
  LSGG: { name: "Geneva", city: "Geneva", iata: "GVA" },
  LOWW: { name: "Vienna", city: "Vienna", iata: "VIE" },
  LKPR: { name: "Prague Václav Havel", city: "Prague", iata: "PRG" },
  LPPT: { name: "Humberto Delgado", city: "Lisbon", iata: "LIS" },
  LTBA: { name: "Istanbul Atatürk", city: "Istanbul", iata: "ISL" },
  LTFM: { name: "Istanbul", city: "Istanbul", iata: "IST" },
  LTFJ: { name: "Sabiha Gökçen", city: "Istanbul", iata: "SAW" },
  LGAV: { name: "Athens Intl", city: "Athens", iata: "ATH" },
  ESSA: { name: "Stockholm Arlanda", city: "Stockholm", iata: "ARN" },
  EKCH: { name: "Copenhagen", city: "Copenhagen", iata: "CPH" },
  ENGM: { name: "Oslo Gardermoen", city: "Oslo", iata: "OSL" },
  EFHK: { name: "Helsinki-Vantaa", city: "Helsinki", iata: "HEL" },
  EPWA: { name: "Warsaw Chopin", city: "Warsaw", iata: "WAW" },
  LHBP: { name: "Budapest Ferenc Liszt", city: "Budapest", iata: "BUD" },
  UUEE: { name: "Sheremetyevo", city: "Moscow", iata: "SVO" },
  UUDD: { name: "Domodedovo", city: "Moscow", iata: "DME" },
  UUWW: { name: "Vnukovo", city: "Moscow", iata: "VKO" },

  // Middle East / Africa
  OMDB: { name: "Dubai Intl", city: "Dubai", iata: "DXB" },
  OMAA: { name: "Abu Dhabi Intl", city: "Abu Dhabi", iata: "AUH" },
  OTHH: { name: "Hamad Intl", city: "Doha", iata: "DOH" },
  OERK: { name: "King Khalid Intl", city: "Riyadh", iata: "RUH" },
  OEJN: { name: "King Abdulaziz Intl", city: "Jeddah", iata: "JED" },
  OBBI: { name: "Bahrain Intl", city: "Manama", iata: "BAH" },
  LLBG: { name: "Ben Gurion", city: "Tel Aviv", iata: "TLV" },
  HECA: { name: "Cairo Intl", city: "Cairo", iata: "CAI" },
  HAAB: { name: "Bole Intl", city: "Addis Ababa", iata: "ADD" },
  HKJK: { name: "Jomo Kenyatta", city: "Nairobi", iata: "NBO" },
  FAOR: { name: "OR Tambo", city: "Johannesburg", iata: "JNB" },
  FACT: { name: "Cape Town Intl", city: "Cape Town", iata: "CPT" },
  GCLP: { name: "Gran Canaria", city: "Las Palmas", iata: "LPA" },

  // Asia / Oceania
  VHHH: { name: "Hong Kong Intl", city: "Hong Kong", iata: "HKG" },
  ZBAA: { name: "Beijing Capital", city: "Beijing", iata: "PEK" },
  ZBAD: { name: "Beijing Daxing", city: "Beijing", iata: "PKX" },
  ZSPD: { name: "Shanghai Pudong", city: "Shanghai", iata: "PVG" },
  ZSSS: { name: "Shanghai Hongqiao", city: "Shanghai", iata: "SHA" },
  ZGGG: { name: "Guangzhou Baiyun", city: "Guangzhou", iata: "CAN" },
  ZGSZ: { name: "Shenzhen Bao'an", city: "Shenzhen", iata: "SZX" },
  ZUUU: { name: "Chengdu Shuangliu", city: "Chengdu", iata: "CTU" },
  RCTP: { name: "Taoyuan Intl", city: "Taipei", iata: "TPE" },
  RKSI: { name: "Incheon Intl", city: "Seoul", iata: "ICN" },
  RKSS: { name: "Gimpo Intl", city: "Seoul", iata: "GMP" },
  RJTT: { name: "Haneda", city: "Tokyo", iata: "HND" },
  RJAA: { name: "Narita Intl", city: "Tokyo", iata: "NRT" },
  RJBB: { name: "Kansai Intl", city: "Osaka", iata: "KIX" },
  RJOO: { name: "Osaka Itami", city: "Osaka", iata: "ITM" },
  WSSS: { name: "Changi", city: "Singapore", iata: "SIN" },
  WMKK: { name: "Kuala Lumpur Intl", city: "Kuala Lumpur", iata: "KUL" },
  VTBS: { name: "Suvarnabhumi", city: "Bangkok", iata: "BKK" },
  VTBD: { name: "Don Mueang", city: "Bangkok", iata: "DMK" },
  VIDP: { name: "Indira Gandhi Intl", city: "Delhi", iata: "DEL" },
  VABB: { name: "Chhatrapati Shivaji", city: "Mumbai", iata: "BOM" },
  VOBL: { name: "Kempegowda", city: "Bengaluru", iata: "BLR" },
  VOMM: { name: "Chennai Intl", city: "Chennai", iata: "MAA" },
  VECC: { name: "Kolkata Intl", city: "Kolkata", iata: "CCU" },
  VGHS: { name: "Dhaka", city: "Dhaka", iata: "DAC" },
  VVNB: { name: "Noi Bai Intl", city: "Hanoi", iata: "HAN" },
  VVTS: { name: "Tan Son Nhat", city: "Ho Chi Minh City", iata: "SGN" },
  VDPP: { name: "Phnom Penh Intl", city: "Phnom Penh", iata: "PNH" },
  RPLL: { name: "Ninoy Aquino Intl", city: "Manila", iata: "MNL" },
  WIII: { name: "Soekarno-Hatta", city: "Jakarta", iata: "CGK" },
  YSSY: { name: "Kingsford Smith", city: "Sydney", iata: "SYD" },
  YMML: { name: "Melbourne Tullamarine", city: "Melbourne", iata: "MEL" },
  YBBN: { name: "Brisbane", city: "Brisbane", iata: "BNE" },
  YPPH: { name: "Perth", city: "Perth", iata: "PER" },
  NZAA: { name: "Auckland", city: "Auckland", iata: "AKL" },
  NZCH: { name: "Christchurch", city: "Christchurch", iata: "CHC" },

  // South America
  SBGR: { name: "Guarulhos", city: "São Paulo", iata: "GRU" },
  SBGL: { name: "Galeão", city: "Rio de Janeiro", iata: "GIG" },
  SAEZ: { name: "Ezeiza", city: "Buenos Aires", iata: "EZE" },
  SCEL: { name: "Santiago Intl", city: "Santiago", iata: "SCL" },
  SKBO: { name: "El Dorado", city: "Bogotá", iata: "BOG" },
  SPIM: { name: "Jorge Chávez", city: "Lima", iata: "LIM" },
};

export function lookupAirport(icao: string | null | undefined): Airport | null {
  if (!icao) return null;
  const code = icao.trim().toUpperCase();
  return AIRPORTS[code] ?? null;
}
